import html


def build_report(name, df, eda, score, ml=None) -> str:
    rows = "".join(f"<tr><td>{html.escape(str(c))}</td><td>{t}</td><td>{eda['missing_percent'][c]}%</td></tr>"
                   for c, t in eda["column_types"].items())
    ml_html = ""
    if ml and "best_model" in ml:
        fi = "".join(f"<li>{html.escape(str(k))}: {v}</li>" for k, v in ml["feature_importance"].items())
        ml_html = (f"<h2>Model results</h2><p>Task: {ml['task']}. Best model: <b>{ml['best_model']}</b>. "
                   f"Test {ml['metric']}: <b>{ml['test_score']}</b>.</p><p>Cross-validation: {ml['cv_scores']}</p>"
                   f"<h3>Top drivers</h3><ul>{fi}</ul>")
    return f"""<html><head><meta charset='utf-8'><title>DataMind report</title><style>
body{{font-family:Segoe UI,Arial;max-width:800px;margin:0 auto;padding:24px;color:#1f2937;background:#ffffff}}
h1{{color:#7C3AED}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #ddd;padding:6px}}
th{{background:#7C3AED;color:#fff}}.score{{font-size:40px;font-weight:bold;color:#7C3AED}}</style></head><body>
<h1>DataMind analysis report</h1><p>Dataset: <b>{html.escape(name)}</b></p>
<p class='score'>Health score: {score}/100</p>
<p>{eda['rows']} rows, {eda['columns']} columns, {eda['duplicate_rows']} duplicate rows, {eda['numeric_columns']} numeric columns.
Most incomplete column: <b>{html.escape(str(eda['most_missing_column']))}</b>.</p>
<h2>Columns</h2><table><tr><th>Column</th><th>Type</th><th>Missing</th></tr>{rows}</table>
<h2>Strong correlations</h2><p>{eda['high_correlations'] or 'None above 0.7'}</p>
<h2>Outliers (IQR)</h2><p>{eda['outlier_counts'] or 'None'}</p>{ml_html}
<p><i>Generated by DataMind.</i></p></body></html>"""
